CREATE TABLE Avion (
refA INTEGER PRIMARY KEY,
numT INTEGER REFERENCES Type ON DELETE CASCADE,
nbreSiege INTEGER,
dateService DATE);

CREATE TABLE Vol (
refV VARCHAR(10) PRIMARY KEY,
refA INTEGER REFERENCES Avion ON DELETE CASCADE,
villeDepart VARCHAR(30),
villeArrivee VARCHAR(30),
dateDepart DATE,
dateArrivee DATE,
horaireDepart VARCHAR(10),
horaireArrivee VARCHAR(10));

CREATE TABLE Employé (
numPoste INTEGER PRIMARY KEY,
numF INTEGER REFERENCES Fonction ON DELETE CASCADE,
nomE VARCHAR(30),
prenomE VARCHAR(30));


CREATE TABLE Maintenance (
refM INTEGER PRIMARY KEY,
refA INTEGER REFERENCES Avion ON DELETE CASCADE,
numPoste INTEGER REFERENCES Employé,
dateM DATE);

CREATE TABLE Billet (
refB INTEGER PRIMARY KEY,
refV VARCHAR(10) REFERENCES Vol ON DELETE CASCADE,
numPoste INTEGER REFERENCES Employé,
dateE DATE,
numPlace INTEGER);

CREATE TABLE Fonction(
numF INTEGER PRIMARY KEY,
nomF VARCHAR(30));

CREATE TABLE Type (
numT INTEGER PRIMARY KEY,
nomT VARCHAR (30));

CREATE TABLE Membre_équipage (
refV VARCHAR(10) REFERENCES Vol ON DELETE CASCADE,
numPoste INTEGER REFERENCES Employé ON DELETE CASCADE);

CREATE TABLE Equipe_maintenance (
numPoste INTEGER REFERENCES Employé,
refM INTEGER REFERENCES Maintenance ON DELETE CASCADE);
